[package]
name = "repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
lang = { path = "../lang" }
rustyline = "10.1.1"
thiserror = "1.0.38"
