[package]
name = "lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
lazy_static = "1.4.0"
nom = "7.1.3"
thiserror = "1.0.38"
